# **Lab 12: Data Science Review**
---
### **Description**
This lab provides a comprehensive overview of exploratory data analysis (EDA) techniques using Python's pandas library for data manipulation and analysis. Additionally, it explores data visualization using the matplotlib library. Finally, you will gain an exposure to different data wrangling commands. Throughout the notebook, you'll review how to load and manipulate datasets effectively with pandas commands and leverage matplotlib to create insightful visualizations that aid in uncovering patterns, trends, and insights within the data.



### **Lab Structure**
**Part 1**: [Exploratory Data Analysis Review](#p1)

  >  **Part 1.1**: [Basic Commands](#p1.1)

  >  **Part 1.2**: [Further Exploration](#p1.2)

**Part 2**: [Data Visualization Review](#p2)


**Part 3**: [Introduction to Data Wrangling](#p3)




<br>

### **Learning Objectives**
By the end of this lab, we will:
* Understand basic pandas commands for EDA.

* Understand basic matplotlib commands for Data Visualization.

* Recognize how to use basic data wrangling commands.


<br>


### **Resources**
* [EDA with pandas Cheat Sheet](https://docs.google.com/document/d/1xnKJsii1AsRH2t22XtrAh7FzSFGqAR0hAmW4oLYM4MI/edit?usp=drive_link)

* [Data Visualization with matplotlib Cheat Sheet](https://docs.google.com/document/d/1_3hzeIBPvcT6VC-eK-DDGVsKUvdVSvylNepoSLn2-T4/edit?usp=drive_link)

* [Data Wrangling with pandas](https://docs.google.com/document/d/1zZ9ItNrI45AzFaDI21qDLS3Zd1JFZtSRIp8KlTeBIRE/edit?usp=sharing)

<br>

**Before starting, run the code below to import all necessary functions and libraries.**

In [ ]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

<a name="p1"></a>

---
## **Part 1: Exploratory Data Analysis Review**
---

<a name="p1.1"></a>

---
### **Part 1.1: Basic Commands**
---


**Run the code cell below to create the DataFrame.**

In [ ]:
df = pd.DataFrame({'U.S. State': ['California', 'Florida', 'Indiana', 'Texas', 'Pennsylvania'],
        'Population (in millions)': [38, 21, 6.5, 28, 13],
        'Capitol': ['Sacramento', 'Tallahassee', 'Indianapolis', 'Austin', 'Harrisburg'],
        'GDP ($ in billions)': [3700, 1070, 352, 1876, 726]})

#### **Problem #1.1.1**

**Together**, let's inspect what `.head()` tells us about this DataFrame.

#### **Problem #1.1.2**

**Together**, let's determine what datatype `Population (in millions)` is.

#### **Problem #1.1.3**

**Together**, let's print all of the unique values for `GDP ($ in billions)`.

---

#### **Now it's your turn! Try Problems #1.1.4 - 1.1.7 on your own.**

---

#### **Problem #1.1.4**

**Independently**, determine the column names in the dataset.

#### **Problem #1.1.5**

**Independently**, determine the highest `GDP ($ in billions)` in the dataset.

#### **Problem #1.1.6**

**Independently**, determine which states are included in this dataset.

#### **Problem #1.1.7**

**Independently**, determine the range of GDP values among the states?

---

<center>

#### **Wait for Your Instructor to Continue**

---

<a name="p1.2"></a>

---
### **Part 1.2: Further Exploration**
---

#### **Problem #1.2.1**

**Independently**, determine the average `Population (in millions)` size among the U.S. states in the dataset.

#### **Problem #1.2.2**

**Independently,** explore rows 4 and 5. What are the U.S. States listed?

#### **Problem #1.2.3**

**Independently**, determine the total `Population (in millions)` across all states.

#### **Problem #1.2.4**

**Independently**, determine the average `Population (in millions)` of the states.

#### **Problem #1.2.5**

**Independently**, determine the `Population (in millions)` for the 3rd state in the dataset.

#### **Problem #1.2.6**

**Independently**, explore the last row in the dataset.

---

<center>

#### **Wait for Your Instructor to Continue**

---

<a name="p2"></a>

---
## **Part 2: Data Visualization Review**
---

**Run the cell below to load in the data**

In [ ]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vS9jPkeKJ8QUuAl-fFdg3nJPDP6vx1byvIBl4yW8UZZJ9QEscyALJp1eywKeAg7aAffwdKP63D9osF1/pub?gid=169291584&single=true&output=csv"
movie_df = pd.read_csv(url)

movie_df.drop_duplicates(inplace=True)

mean_runtime = movie_df['Runtime'].mean()
movie_df['Runtime'] = movie_df['Runtime'].fillna(mean_runtime)

movie_df = movie_df.rename(columns = {"Runtime": "Runtime (min)"})
movie_df = movie_df.astype({"Runtime (min)": "int64"})

movie_df.head()

,Series_Title,Released_Year,Runtime (min),Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,142,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469
1,The Godfather,1972,175,Crime,9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411
2,The Dark Knight,2008,152,Action,9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444
3,The Godfather: Part II,1974,202,Crime,9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000
4,12 Angry Men,1957,96,Crime,9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000

#### **Problem #2.1**

**Together**, let's create a scatterplot using `Runtime (min)` as the x-axis value and `Gross` as the y-axis value.

Make sure to include a meaningful:
* `Title`: "Gross Money vs. Runtime:
* `X-axis`: "Gross (USD)"
* `Y-axis`: "Runtime (min)"

#### **Problem #2.2**

**Together**, let's create a line plot using `Runtime (min)` as the x-axis value and `Gross` as the y-axis value.

Make sure to include a meaningful:
* Title, ex: `'Gross Money vs. Runtime'`.
* X-axis label including units `'min'`.
* Y-axis label including units `'USD'`.

<br>

**NOTE**: This is not going to be a particularly helpful graph (the scatter plot is a better choice), but we oftentimes will not know this ahead of time. A lot of EDA and visualizations involves trying a number of things and seeing what is useful.

#### **Problem #2.3**

**Independently**, create a scatterplot using `Released_Year` as the x-axis value and `Runtime (min)` as the y-axis value.

Make sure to include a meaningful:
* `Title`: "Runtime vs. Released_Year"
* `X-axis`: "Year"
* `Y-axis`: "Runtime (min)"

#### **Problem #2.4**

**Independently**, create a line plot using `Released_Year` as the x-axis value and `Average Gross in Year` as the y-axis value.

Make sure to include a meaningful:
* Title, ex: `'Average Gross Money vs. Released Year'`.
* X-axis label.
* Y-axis label including units `'USD'`.

In [ ]:
mean_gross = movie_df.groupby('Released_Year')['Gross'].mean()

plt.plot(mean_gross.index, # COMPLETE THIS CODE

#### **Problem #2.5**

**Independently**, create a bar plot of the number of movies released per year.

Use the DataFrame provided, `movies_per_year` and make sure to include a meaningful:
* Title.
* X-axis label.
* Y-axis label.

In [ ]:
movies_per_year = movie_df['Released_Year'].value_counts()

plt.bar(movies_per_year.index, # COMPLETE THIS CODE

<a name="p3"></a>

---
## **Part 3: Data Wrangling**
---

Take a moment to explore the created dataframe in the cell below, which contains the names of famous NBA players, ages, heights and their respective teams.

<br>


**Run the cell below to load the DataFrame before continuing.**

In [ ]:
df = pd.DataFrame(
  {'Name':['Giannis Antetokounmpo','Kevin Durant','Stephen Curry','Nikola Jokic', 'Joel Embiid', 'LeBron James'],
  'Age':[28, 34, 34, 27, np.nan, 38],
   'Number':[34, 35, 30, 15, 21, 23],
  'Height (in)':[83, 82, 74, 83, np.nan, 81],
  'Team':['Milwaukee Bucks', np.nan, 'Golden State Warriors', 'Denver Nuggets', np.nan, 'Los Angeles Lakers'],
   'Favorite Color':['Blue', 'Black', 'Grey', 'Green', 'Blue', 'Purple']})

df.head()

,Name,Age,Number,Height (in),Team,Favorite Color
0,Giannis Antetokounmpo,28.0,34,83.0,Milwaukee Bucks,Blue
1,Kevin Durant,34.0,35,82.0,NaN,Black
2,Stephen Curry,34.0,30,74.0,Golden State Warriors,Grey
3,Nikola Jokic,27.0,15,83.0,Denver Nuggets,Green
4,Joel Embiid,NaN,21,NaN,NaN,Blue

### **Problem #3.1**

**Together**, let's find the non-null count to determine if there is any missing data.

### **Problem #3.2**

**Together**, let's use `isnull()` to see which values are missing.

### **Problem #3.3**

**Independently**, drop the row with Joel Embiid's data since it is missing.

### **Problem #3.3**

**Independently**, drop the `Number` column.

### **Problem #3.4**

Remove the `Favorite Color` feature.

### **Problem #3.5**

Create a `Height (ft)` column so that it shows the player's height in feet.

---

# End of Notebook

© 2024 The Coding School, All rights reserved