# **Homework 12: Data Science Review**
---
### **Description**
Throughout this notebook, you'll review how to load and manipulate datasets effectively with pandas commands and leverage matplotlib to create insightful visualizations that aid in uncovering patterns, trends, and insights within the data.



### **Lab Structure**
**Part 1**: [Data Science Review](#p1)

**Part 2**: [Data Wrangling](#p2)





<br>


### **Resources**
* [EDA with pandas Cheat Sheet](https://docs.google.com/document/d/1xnKJsii1AsRH2t22XtrAh7FzSFGqAR0hAmW4oLYM4MI/edit?usp=drive_link)

* [Data Visualization with matplotlib Cheat Sheet](https://docs.google.com/document/d/1_3hzeIBPvcT6VC-eK-DDGVsKUvdVSvylNepoSLn2-T4/edit?usp=drive_link)

* [Data Wrangling with pandas](https://docs.google.com/document/d/1zZ9ItNrI45AzFaDI21qDLS3Zd1JFZtSRIp8KlTeBIRE/edit?usp=sharing)



<br>

**Before starting, run the code below to import all necessary functions and libraries.**

In [ ]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

<a name="p1"></a>

---
## **Part 1: Exploratory Data Analysis Review**
---



**Run the code cell below to create the DataFrame.**

In [ ]:
df = pd.DataFrame({'River': ['Nile', 'Amazon', 'Yangtze', 'Mississippi', 'Yenisei'],
                   'Continent': ['Africa', 'South America', 'Asia', 'North America', 'Asia'],
                   'Length (km)': [6650, 6575, 6300, 6275, 5540],
                   'Countries': ['Egypt, Sudan, South Sudan, Ethiopia, Uganda, Congo, Kenya, Tanzania, Rwanda, Burundi',
                                 'Brazil, Peru, Bolivia, Colombia, Ecuador, Venezuela, Guyana',
                                 'China',
                                 'United States',
                                 'Russia']})

#### **Problem #1.1**

Inspect what `.head()` tells us about this DataFrame.

#### **Problem #1.2**

 Determine the names of the columns in this dataset.

#### **Problem #1.3**

Find out the length of the longest river in the dataset.

#### **Problem #1.4**

List all the continents included in this dataset.

#### **Problem #1.5**

Calculate the average length of the rivers in the dataset.

#### **Problem #1.6**

Determine which countries are included in this dataset.

#### **Problem #1.7**

**Independently**, determine the total length of all rivers in this dataset combined.

#### **Problem #1.8**

Create a visualization with `River` on the x-axis and `Length (km)` on the y-axis. It is up to you to decide which visualization to create. Include a meaningful title and axes labels.

<a name="p2"></a>

---
## **Part 2: Data Wrangling**
---

<br>


**Run the cell below to load the DataFrame before continuing.**

In [ ]:
df_cars = pd.DataFrame(
    {'Car Model': ['Toyota Camry', 'Honda Accord', 'Ford Mustang', 'Tesla Model 3', 'Chevrolet Camaro', 'BMW 3 Series'],
     'Year': [2020, 2019, 2018, None, 2021, 2022],
     'Mileage (thousands)': [15, 30, 45, 20, None, 10],
     'Ground Clearance (in)': [5.7, 5.8, 5.5, 4.5, 4.7, None],
     'Manufacturer': ['Toyota', 'Honda', 'Ford', None, 'Chevrolet', 'BMW'],
     'Favorite Feature': ['Fuel Efficiency', 'Reliability', 'Power', 'Autopilot', 'Design', 'Comfort']}
)

df_cars

### **Problem #2.1**

Find the non-null count to determine if there is any missing data.

### **Problem #2.2**

Use `isnull()` to see which values are missing.

### **Problem #2.3**

Drop the row with `BMW 3 Series` information.

In [ ]:
df_cars = # COMPLETE THIS CODE

### **Problem #2.4**

Drop the `Year` column.

### **Problem #2.4**

Remove the `Favorite Feature` feature.

### **Problem #2.5**

Create a `Ground Clearance (ft)` column so that it shows the Ground Clearance in feet.

---

# End of Notebook

Â© 2024 The Coding School, All rights reserved